on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Check out code
        uses: actions/checkout@v1
      - name: Test
        run: CGO_ENABLED=0 go test ./... -v
